### ISSUE TITLE
立个小flag 2.9之前leetcode刷到500题

### ISSUE THREAD

**Issue by wfnuser** [wfnuser/leetcode#2]
哈哈 最近要放假了，工作上事情变少了，估摸着一天如果刷10个小时，刷10天的话，平均leetcode的easy medium差不多20分钟一道 应该至少可以300道左右 上个月差不多做了150左右 2.9号前刷到500道还留了挺多余量的 达成的话，之后面试除了海外几家公司应该算法题不会太慌了

**Comment by wfnuser** [comment]
2020.1.19  solved += 6

**Comment by wfnuser** [comment]
2020.1.20 solved += 3
2020.1.21 solved += 20

**Comment by chasingegg** [comment]
厉害厉害，给大佬点star

**Comment by wfnuser** [comment]
2020.1.22 solved += 35

**Comment by wfnuser** [comment]
> 厉害厉害，给大佬点star

还是c++大佬厉害

**Comment by wfnuser** [comment]
2020.1.23 solved += 25

**Comment by wfnuser** [comment]
2020.1.24 solved += 7
今天除夕 吃了不少东西 做的少点

**Comment by wfnuser** [comment]
前500的easy题目基本上都扫空了 大年初一正式进入下一阶段的难度

**Comment by wfnuser** [comment]
截止2020.1.25 13:13通过前500题所有easy题目

**Comment by wfnuser** [comment]
2020.1.25 solved += 15

**Comment by wfnuser** [comment]
2020.1.26 solved += 17

**Comment by wfnuser** [comment]
2020.1.27 solved += 12
按照这个进度下去有点悬... 做饭花的时间太多了... 而且整天都刷题确实也有点刷不动

**Comment by wfnuser** [comment]
2020.1.28 solved += 8
估计是来不及了... 不过至少可以到400道 今天和小伙伴开始讨论怎么样给抗击新冠做一些贡献，讨论了一个产品原型，也可能是伪需求 但希望可以起到一定作用 武汉加油

**Comment by wfnuser** [comment]
放弃放弃 临时多了点其他需求... 刷到400吧，应该也勉强可以应付大部分面试了吧

**Comment by haithink** [comment]
思考一段时间做不出来的题目会看答案么？

**Comment by wfnuser** [comment]
> 思考一段时间做不出来的题目会看答案么？

哈哈哈 肯定会呀 一般想一会想不出来就留着，每天碎片时间想想 还是想不出来就看答案～

**Comment by wfnuser** [comment]
> 思考一段时间做不出来的题目会看答案么？

大佬可以顺手帮我项目点个star是最好的 哈哈
https://github.com/wfnuser/burrow

**Comment by haithink** [comment]
> > 思考一段时间做不出来的题目会看答案么？
> 
> 大佬可以顺手帮我项目点个star是最好的 哈哈
> https://github.com/wfnuser/burrow

哈哈，点了。我也不是什么大佬。还在阿里么？我以前在阿里也待过一年。

**Comment by wfnuser** [comment]
> > > 思考一段时间做不出来的题目会看答案么？
> > 
> > 
> > 大佬可以顺手帮我项目点个star是最好的 哈哈
> > https://github.com/wfnuser/burrow
> 
> 哈哈，点了。我也不是什么大佬。还在阿里么？我以前在阿里也待过一年。

在 说不定要撤离了呢... 估计在这发应该也不会有同事看到 哈哈
有好机会分享嘛
